In [1]:
import numpy as np
import sympy as sp

In [2]:
#Q3
np.random.seed(28)
A = np.random.randint(0, 10, size=(5, 5))
sp.Matrix(A)
U,S,VT=np.linalg.svd(A)
print('U=',U)
print('S=',S)
print("VT=",VT)


U= [[-0.5127523  -0.34299748  0.03986648 -0.7000646  -0.35743255]
 [-0.23812406 -0.67855958  0.19056258  0.19073499  0.64043727]
 [-0.60981807 -0.02896036 -0.15242039  0.66094038 -0.40891205]
 [-0.49603837  0.52107772 -0.39177483 -0.19049929  0.54096806]
 [-0.24989972  0.38671557  0.88621503  0.01993886  0.04718644]]
S= [22.65504915  8.44536654  5.89086971  5.49001171  2.56553258]
VT= [[-0.41930983 -0.52308436 -0.42397669 -0.53766324 -0.28587414]
 [ 0.5663518  -0.19181095 -0.7312305   0.32803508 -0.01221267]
 [-0.25507775 -0.43695411 -0.01321834  0.1867741   0.84199   ]
 [ 0.44851275 -0.68436459  0.53403267  0.00798431 -0.21266587]
 [ 0.48702829  0.17409058 -0.01342028 -0.75389848  0.40491098]]


In [3]:
USVT = np.dot(U, np.dot(np.diag(S), VT))

In [4]:
verification = np.allclose(USVT, A)

if verification:
    print("A equals the product of USVT.")
else:
    print("A does not equal the product of USVT.")

A equals the product of USVT.
